version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: ./FE/Dockerfile
    expose:
      - 3000
    ports:
      - "3000:3000"
    volumes:
      - ./FE:/frontend
      - /frontend/node_modules
    #     stdin_open: true
    #     tty: true
    restart: always

  backend:
    build:
      context: .
      dockerfile: ./BE/Dockerfile
    expose:
      - 8080
    network_mode: "host"
    volumes:
      - ./build/libs/:/backend
    restart: always
    stdin_open: true
    tty: true

  nginx:
    image: nginx:latest
    ports:
      - "3001:3001"
      - "8081:8081"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    restart: "on-failure"